name: Renovate
on:
  workflow_dispatch: {}
  schedule:
    # run every 15th minute between 9am and 5pm (4am and 12pm UTC), M-F
    - cron: "0/15 14-22 * * 1-5"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Renovate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RENOVATE_THM_APP_ID_PUB }}
          private-key: ${{ secrets.RENOVATE_THM_PRIVATE_KEY_PUB }}
      - uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@2e021d24483d81e77e0e902d0809adfbfff276fc # v40.1.10
        with:
          # options in this file are defined by
          # https://docs.renovatebot.com/self-hosted-configuration/
          configurationFile: .github/renovate-config.json
          token: ${{ steps.app-token.outputs.token }}
